export interface Vehicle{
    fuelType: any,
    rating: any,
    renterTripsTaken: any,
    reviewCount: any,
    locationcity: any,
    locationcountry: any,
    locationlatitude: any,
    locationlongitude: any,
    locationstate: any,
    ownerid: any,
    ratedaily: any,
    vehiclemake: any,
    vehiclemodel: any,
    vehicletype: any,
    vehicleyear: any,
}